configuration: Release
image: Visual Studio 2017
platform: x64
version: "{build}"

build:
  verbosity: normal

install:
    - set PATH=%PATH%;C:\mingw-w64\x86_64-7.2.0-posix-seh-rt_v5-rev1\mingw64\bin
    - set PATH=%PATH%;C:\Python37-x64

build_script:
  - bash ./setup.sh

